### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by outloudvi** [SchOJ/dmoj-site#1]
* [ ] Switch to Arch Linux or Alpine as base OS
* [ ] FIix outdated nginx
* [ ] Look in db problems
